@file:Suppress("NonAsciiCharacters", "ObjectPropertyName")
package nl.jhvh.sudoku.format.boxformat

const val `boxChar ║`: Char = '║'
const val `boxChar │`: Char = '│'
const val `boxChar ═`: Char = '═'
const val `boxChar ─`: Char = '─'
const val `boxChar ╔`: Char = '╔'
const val `boxChar ╗`: Char = '╗'
const val `boxChar ╚`: Char = '╚'
const val `boxChar ╝`: Char = '╝'
const val `boxChar ╤`: Char = '╤'
const val `boxChar ╧`: Char = '╧'
const val `boxChar ╦`: Char = '╦'
const val `boxChar ╩`: Char = '╩'
const val `boxChar ╟`: Char = '╟'
const val `boxChar ╢`: Char = '╢'
const val `boxChar ╠`: Char = '╠'
const val `boxChar ╣`: Char = '╣'
const val `boxChar ╬`: Char = '╬'
const val `boxChar ┼`: Char = '┼'
const val `boxChar ╪`: Char = '╪'
const val `boxChar ╫`: Char = '╫'
